// Список действий, которые пользователь может выполнить с помощью сервера
// в системе ДУ-58
module.exports = {
  // Рабочие распоряжения
  GET_WORK_ORDERS: 'GET_WORK_ORDERS',
  REPORT_ON_ORDER_DELIVERY: 'REPORT_ON_ORDER_DELIVERY',
  CONFIRM_ORDER: 'CONFIRM_ORDER',
  CONFIRM_ORDER_FOR_OTHER_RECEIVERS: 'CONFIRM_ORDER_FOR_OTHER_RECEIVERS',
  CONFIRM_ORDER_FOR_OTHERS: 'CONFIRM_ORDER_FOR_OTHERS',
  DEL_CONFIRMED_ORDERS_FROM_CHAIN: 'DEL_CONFIRMED_ORDERS_FROM_CHAIN',
  DEL_STATION_WORK_PLACE_RECEIVER: 'DEL_STATION_WORK_PLACE_RECEIVER',
  // Все распоряжения
  ADD_ORDER: 'ADD_ORDER',
  MOD_ORDER: 'MOD_ORDER',
  GET_DATA_FOR_GID: 'GET_DATA_FOR_GID',
  GET_ORDERS_ADDRESSED_TO_GIVEN_WORK_POLIGON_FROM_GIVEN_DATE: 'GET_ORDERS_ADDRESSED_TO_GIVEN_WORK_POLIGON_FROM_GIVEN_DATE',
  GET_ORDERS_JOURNAL_DATA: 'GET_ORDERS_JOURNAL_DATA',
  // Параметры последних изданных распоряжений
  GET_LAST_ORDERS_PARAMS: 'GET_LAST_ORDERS_PARAMS',
  // Черновики распоряжений
  ADD_ORDER_DRAFT: 'ADD_ORDER_DRAFT',
  DEL_ORDER_DRAFT: 'DEL_ORDER_DRAFT',
  MOD_ORDER_DRAFT: 'MOD_ORDER_DRAFT',
  GET_ORDER_DRAFTS: 'GET_ORDER_DRAFTS',
  // "Окна"
  GET_OKNAS: 'GET_OKNAS',
};
